name: Docker Lint Check

on:
  push:
    branches:
      - main # Change this to the branch you are working on if different from main

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Run Dockerfile lint check
      run: |
        docker run --rm -v $(pwd):/app:ro hadolint/hadolint < Dockerfile
